#language slang 2026
module Constants;

public static const int PRIMITIVE_SPHERE = 0;
public static const int PRIMITIVE_QUAD = 1;
public static const int PRIMITIVE_TRI = 2;
public static const int PRIMITIVE_MESH = 3;

public static const int TLAS_STACK_SIZE = 16;
public static const int BLAS_STACK_SIZE = 32;

public static const float PI = 3.14159265358979323846f;
public static const float TWO_PI = 6.28318530717958647692f;
public static const float EPSILON = 1.0e-8f;
public static const float RAY_EPSILON = 1.0e-3f;
public static const float MAX_RAY_DISTANCE = 1.0e30f;

